version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: greenquest_app
    restart: unless-stopped
    expose:
      - "9000"
    environment:
      CORS_ALLOW_ORIGIN: '^http://54\.37\.14\.239$'
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:alpine
    container_name: greenquest_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8
    container_name: greenquest_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: greenquest
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  nginx_certs:
  nginx_vhost:
  nginx_html:
  mysql_data:
